import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Montserrat, Figtree } from "next/font/google";
import "./globals.css";
import { SmoothScroll } from "@/components/smooth-scroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({ 
  subsets: ["latin"],
  weight: ["700"], // Bold
  variable: "--font-montserrat",
});

const figtree = Figtree({ 
  subsets: ["latin"],
  variable: "--font-figtree",
  weight: ["400", "700"],
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans", // This creates the variable
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistMono.variable} ${geistSans.variable} ${montserrat.variable} ${openSans.variable} ${figtree.variable} antialiased`} suppressHydrationWarning={true}>
        <SmoothScroll>
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
